# Generated by Django 4.1.7 on 2023-04-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app51325', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cli_nombre', models.CharField(max_length=20)),
                ('cod_prod', models.IntegerField()),
                ('nombre', models.CharField(max_length=15)),
                ('cantidad_unidades', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='nombre',
            new_name='provee_nombre',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cli_nombre',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='cod_prod',
            field=models.IntegerField(default=int),
            preserve_default=False,
        ),
    ]
